<?php

namespace App\Console\Commands;

use App\Services\ShopifyService;
use Illuminate\Console\Command;

class ShopifySetup extends Command
{
    protected $signature   = 'shopify:setup';
    protected $description = 'Setup Shopify integration: verify connection, register webhooks, inject button';

    public function handle(): void
    {
        $shopify = app(ShopifyService::class);

        // Step 1: Verify connection
        $this->info('🔌 Checking Shopify connection...');

        $shop = $shopify->getShopInfo();

        if (!$shop) {
            $this->error('❌ Cannot connect to Shopify. Check your .env credentials:');
            $this->error('   SHOPIFY_STORE_DOMAIN');
            $this->error('   SHOPIFY_ACCESS_TOKEN');
            return;
        }

        $this->info("✅ Connected to: {$shop['name']}");
        $this->info("   Domain: {$shop['myshopifyDomain']}");
        $this->info("   Plan: {$shop['plan']['displayName']}");
        $this->info("   Currency: {$shop['currencyCode']}");
        $this->line('');

        // Step 2: Register webhooks
        $this->info('📡 Registering webhooks...');

        $webhookResults = $shopify->registerWebhooks();

        foreach ($webhookResults as $topic => $result) {
            if ($result['success']) {
                $this->info("   ✅ {$topic}");
            } else {
                $this->warn("   ⚠️ {$topic}: {$result['error']}");
            }
        }

        $this->line('');

        // Step 3: Inject theme button
        if ($this->confirm('📦 Inject QuickPay button into active theme?', true)) {
            $this->info('💉 Injecting button snippet...');

            $snippet = $this->getButtonSnippet();
            $result  = $shopify->injectThemeSnippet($snippet);

            if ($result['success']) {
                $this->info('✅ Button snippet injected successfully!');
                $this->info('');
                $this->info('➡️ Now add this to your product template:');
                $this->info('   {% render \'quickpay-button\' %}');
                $this->info('');
                $this->info('   Edit: Online Store → Themes → Edit code');
                $this->info('   Open: templates/product.json or sections/main-product.liquid');
                $this->info('   Add the line after the "Add to Cart" button');
            } else {
                $this->error("❌ Injection failed: {$result['error']}");
            }
        }

        $this->line('');
        $this->info('🎉 Shopify setup complete!');
    }

    private function getButtonSnippet(): string
    {
        $appUrl = config('app.url');

        return <<<LIQUID
{%- comment -%}
  QuickPay Checkout Button
  Bypasses Shopify Checkout → Redirects to Stripe via QuickPay
  Generated by: php artisan shopify:setup
  Version: 1.0.0
{%- endcomment -%}

<div id="quickpay-wrap" style="margin-top:12px;">
  <button
    type="button"
    id="quickpay-btn"
    data-product-id="{{ product.id }}"
    data-variant-id="{{ product.selected_or_first_available_variant.id }}"
    data-title="{{ product.title | escape }}"
    data-variant="{{ product.selected_or_first_available_variant.title | escape }}"
    data-price="{{ product.selected_or_first_available_variant.price }}"
    data-currency="{{ cart.currency.iso_code }}"
    data-image="{{ product.featured_image | img_url: '400x400' }}"
    {% unless product.selected_or_first_available_variant.available %}disabled{% endunless %}
    style="
      width:100%;padding:16px 24px;
      background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);
      color:white;border:none;border-radius:8px;font-size:16px;font-weight:600;
      cursor:pointer;display:flex;align-items:center;justify-content:center;gap:8px;
      margin-top:8px;transition:all 0.3s ease;
    "
    onmouseover="this.style.transform='translateY(-2px)';this.style.boxShadow='0 8px 20px rgba(102,126,234,0.4)'"
    onmouseout="this.style.transform='';this.style.boxShadow=''"
  >
    {% if product.selected_or_first_available_variant.available %}
      ⚡ Buy Now — Secure Checkout
    {% else %}
      Sold Out
    {% endif %}
  </button>

  <div id="qp-status" style="display:none;text-align:center;padding:10px;color:#667eea;font-size:14px;font-weight:500;"></div>
  <div id="qp-error" style="display:none;padding:10px 14px;margin-top:8px;background:#fff5f5;border:1px solid #fc8181;border-radius:6px;color:#c53030;font-size:13px;text-align:center;"></div>

  <div style="display:flex;gap:6px;flex-wrap:wrap;justify-content:center;margin-top:10px;">
    <span style="font-size:11px;color:#718096;background:#f7fafc;border:1px solid #e2e8f0;border-radius:20px;padding:3px 10px;">🔒 SSL</span>
    <span style="font-size:11px;color:#718096;background:#f7fafc;border:1px solid #e2e8f0;border-radius:20px;padding:3px 10px;">💳 All Cards</span>
    <span style="font-size:11px;color:#718096;background:#f7fafc;border:1px solid #e2e8f0;border-radius:20px;padding:3px 10px;">🍎 Apple Pay</span>
    <span style="font-size:11px;color:#718096;background:#f7fafc;border:1px solid #e2e8f0;border-radius:20px;padding:3px 10px;">G Pay</span>
  </div>
</div>

<script>
(function(){
  'use strict';
  var QPURL='$appUrl';
  var btn=document.getElementById('quickpay-btn');
  var sts=document.getElementById('qp-status');
  var err=document.getElementById('qp-error');
  if(!btn)return;

  function show(msg){sts.textContent=msg;sts.style.display='block';err.style.display='none';btn.disabled=true;btn.style.opacity='0.7';}
  function fail(msg){err.textContent='⚠️ '+msg;err.style.display='block';sts.style.display='none';btn.disabled=false;btn.style.opacity='1';}

  document.addEventListener('variant:changed',function(e){
    if(!e.detail||!e.detail.variant)return;
    var v=e.detail.variant;
    btn.dataset.variantId=v.id;
    btn.dataset.price=v.price;
    btn.dataset.variant=v.title;
    btn.disabled=!v.available;
  });

  function qty(){var e=document.querySelector('[name="quantity"]');return e?Math.max(1,parseInt(e.value)||1):1;}
  function shop(){return(window.Shopify&&window.Shopify.shop)?window.Shopify.shop:window.location.hostname;}

  function xhr(method,url,data){
    return new Promise(function(ok,no){
      var x=new XMLHttpRequest();
      x.open(method,url,true);
      x.setRequestHeader('Content-Type','application/json');
      x.setRequestHeader('Accept','application/json');
      x.timeout=30000;
      x.onreadystatechange=function(){
        if(x.readyState!==4)return;
        try{ok(JSON.parse(x.responseText));}catch(e){no(new Error('Invalid response'));}
      };
      x.onerror=function(){no(new Error('Network error'));};
      x.ontimeout=function(){no(new Error('Timeout'));};
      x.send(data?JSON.stringify(data):null);
    });
  }

  btn.addEventListener('click',function(){
    var vid=btn.dataset.variantId;
    var pid=btn.dataset.productId;
    var title=btn.dataset.title||'Product';
    var vtitle=btn.dataset.variant||'';
    var price=parseInt(btn.dataset.price||'0');
    var cur=btn.dataset.currency||'USD';
    var img=btn.dataset.image||'';
    var q=qty();

    if(!vid||vid==='undefined'){fail('Select an option first');return;}
    if(price<=0){fail('Invalid price');return;}

    show('⏳ Adding to cart...');

    xhr('POST','/cart/add.js',{id:parseInt(vid),quantity:q})
    .then(function(){show('⏳ Preparing checkout...');return xhr('GET','/cart.js');})
    .then(function(cart){
      show('⏳ Creating secure checkout...');
      return xhr('POST',QPURL+'/shopify/cart',{
        shop_domain:shop(),
        cart_token:cart.token||'',
        currency:cur,
        subtotal:price*q,
        items:[{
          product_id:parseInt(pid)||0,
          variant_id:parseInt(vid),
          quantity:q,
          title:title,
          variant_title:vtitle,
          price:price,
          image:img
        }]
      });
    })
    .then(function(d){
      if(d.error){fail(d.error.message||'Failed');return;}
      if(!d.checkout_url){fail('No checkout URL');return;}
      show('✅ Redirecting...');
      setTimeout(function(){window.location.href=d.checkout_url;},300);
    })
    .catch(function(e){fail(e.message||'Something went wrong');});
  });

  console.log('QuickPay v1.0 loaded',{variant:btn.dataset.variantId,url:QPURL});
}());
</script>
LIQUID;
    }
}